version: '3.3'

services:
  adelya:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./media:/home/app/web/media
      - ./static:/home/app/web/static
    command: >
      gunicorn core.wsgi:application --bind 0.0.0.0:666 --access-logfile -
    ports:
      - "666:666"


volumes:
  static_volume:
  media_volume: